name: startriage
summary: Application to keep track of updates on a Discourse server
description: |
  Triaging of current bugs, pull requests, discourse posts, etc for Ubuntu.

base: core24
type: app
version: git
confinement: strict
grade: beta

apps:
  startriage:
    command: bin/startriage
    plugs:
      - network
      - network-bind

parts:
  startriage:
    plugin: python
    source: https://github.com/ubuntu/startriage
    source-type: git
    #stage-packages:
    #  - python3-launchpadlib
    #  - python3-debian

layout:
  /etc/startriage.conf:
    bind-file: $SNAP_DATA/etc/startriage.conf
