"""Shared StrEnum types used across startriage modules."""

from __future__ import annotations

from enum import StrEnum


class UpdateFilter(StrEnum):
    """Controls which bugs are shown based on who last acted on them."""

    theirs = "theirs"  # show only bugs where non-team member acted last
    ours = "ours"  # show only bugs where team member acted last
    all = "all"  # show all bugs regardless of last actor


class FetchMode(StrEnum):
    """Bug analysis mode."""

    triage = "triage"  # date-range bugs for daily triage
    todo = "todo"  # tag-filtered housekeeping bugs
    subscribed = "subscribed"  # list subscribed bugs


class AIProvider(StrEnum):
    """LLM backend used for agentic triage."""

    copilot = "copilot"  # GitHub Copilot SDK (default); GitHub token auth
    openrouter = "openrouter"  # OpenAI-compatible BYOK endpoint


class TriageStatus(StrEnum):
    """Status the agent recommends for a triaged bug."""

    invalid = "Invalid"  # not a bug, or already fixed in the reported version
    incomplete = "Incomplete"  # more information needed from the reporter
    triaged = "Triaged"  # valid and reproducible
    duplicate = "Duplicate"  # duplicate of another report
    no_change = "no-change"  # leave as-is; needs further engineering input


class ProposedFixKind(StrEnum):
    """How the agent's proposed fix should be interpreted."""

    none = "none"  # no fix proposed
    reference = "reference"  # value is a URL/commit pointing at an existing fix
    diff = "diff"  # value is a unified diff generated by the agent
